# Generated by Django 4.0.10 on 2023-10-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('blurb', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=80)),
                ('start_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
