# Generated by Django 4.0.10 on 2023-10-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event_name', models.CharField(max_length=100)),
                ('cta_text', models.CharField(max_length=280)),
                ('bot_name', models.CharField(max_length=15)),
                ('event_date', models.DateTimeField()),
            ],
            options={
                'ordering': ['event_date'],
            },
        ),
    ]
