# Generated by Django 4.0.10 on 2023-10-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cta_text',
            field=models.TextField(max_length=280),
        ),
    ]
